package androidx.essentials.playground

enum class Preference {
    AUTO_COMPLETE,
    BOOLEAN,
    DESTINATION,
    END_DATE,
    END_TIME,
    FILTER,
    FLOAT,
    INT,
    IS_CHECKABLE,
    IS_DRAGGABLE,
    IS_EDITABLE,
    IS_HIDEABLE,
    IS_MANDATORY,
    IS_HINT_ENABLED,
    KEYBOARD,
    LONG,
    IS_SINGLE_SELECTION,
    SKIP_COLLAPSED,
    START_DATE,
    START_TIME,
    STRING,
    TEXT_INPUT,
}